import turtle
t = turtle.Turtle()
t.shape("turtle")
t.pensize(5)
side = 20
angle = 90

t.color("red")
t.forward(side) 
t.right(angle)
t.forward(side) 
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)

side +=20

t.color("orange")
t.forward(side) 
t.right(angle)
t.forward(side) 
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)

side +=20

t.color("yellow")
t.forward(side) 
t.right(angle)
t.forward(side) 
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)


side +=20

t.color("green")
t.forward(side) 
t.right(angle)
t.forward(side) 
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)

side +=20

t.color("blue")
t.forward(side) 
t.right(angle)
t.forward(side) 
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
t.right(angle)
t.forward(side)
